[test-shared.nixos]
check = "./check.sh"
serialize = "./serialize.sh"

[test-shared.home]
check = "./check.sh"
serialize = "./serialize.sh"

[test-shared.shared]
check = "./shared_check.sh"
serialize = "./shared_serialize.sh"