= How to define backends

This page explains how to author a backend that integrates with nixos-artifacts.
A backend implements serialization and deserialization of artifact files. Backends can be packaged as separate flakes and plugged into a project.

WARNING: The backend interface is experimental and may change.

== Environment Variables and Directories

Backends operate on temporary directories.
Everything the generator script should use, is handed over via files, directories and environment variables.

Every script gets always these environment variables:


== Backend Phases/Scripts

If the Script returns an exit code other than 0 the whole process will be aboard.

=== check_configuration

This step is to verify validity of `$config` which is rendered by `artifacts.config.<backend-name>`.

=== check_serialization

Is called during `generate` to check if the requested artifact already exists, to prevent overriding existing artifacts.

.Variables at runtime:

- `$inputs` directory containing all files that should exist. Each file is a json object containing the information defined in your nixosConfiguration (`artifacts.store.<artifact>.file`)
- `$config` a json file containing `artifacts.config.<backend-name>` as json.
- `$machine` holding a string of the machine name
- `$artifact` holding a string of the artifact name, which is processed at the moment.

=== serialize

Is called if a generator script successfully created secrets.

.Variables at runtime:

- `$out` directory containing all files generated by the generator script.
- `$config` a json file containing `artifacts.config.<backend-name>` as json.
- `$machine` holding a string of the machine name
- `$artifact` holding a string of the artifact name, which is processed at the moment.

=== deserialize

NOTE: write me!
