== artifacts{zwsp}.default{zwsp}.backend{zwsp}.serialization

script for serialization



__Type:__ string



== artifacts{zwsp}.store



Artifacts store definitions



__Type:__ attribute set of (submodule)



__Default:__

[source,nix]
----
{ }
----



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.description



Optional description of the artifact for documentation purposes{zwsp}.



__Type:__ null or string



__Default:__

[source,nix]
----
null
----



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.files



file definition on the target system



__Type:__ attribute set of (submodule)



__Default:__

[source,nix]
----
{ }
----



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.files{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.group



group of the file on the target system{zwsp}.



__Type:__ string



__Default:__

[source,nix]
----
"root"
----



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.files{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.mode



Permissions mode of the decrypted secret in a format understood by chmod{zwsp}.



__Type:__ string



__Default:__

[source,nix]
----
"0400"
----



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.files{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.owner



owner of the file on the target system{zwsp}.



__Type:__ string



__Default:__

[source,nix]
----
"root"
----



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.files{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.path



Path to the file on the target system{zwsp}.



__Type:__ string



__Default:__

[source,nix]
----
/run/artifacts/<artifact-name>/<file-name>
----



__Example:__

[source,nix]
----
"/etc/ssh/ssh_host_ed25519_key"
----



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.generator



Generator Script{zwsp}. These environment variables are handed over to this script{zwsp}.

[options="compact"]
* {empty}``$out`` a folder the generator script must create a file for each file definition of the artifact{zwsp}.

* {empty}``$prompts`` a folder containing files containing the prompt inputs (defined by the prompts option){zwsp}.

* {empty}``$artifact`` artifact name{zwsp}.

* {empty}``$artifact_context`` context type: “nixos”, “homemanager”, or “shared”{zwsp}.

* {empty}``$machine`` machine name (only for NixOS targets){zwsp}.

* {empty}``$username`` username (only for Home Manager targets){zwsp}.

* {empty}``$LOG_LEVEL`` log level{zwsp}.




__Type:__ null or package



__Default:__

[source,nix]
----
null
----



__Example:__

[source,nix]
----
pkgs.write.writeBash "random" ''
  ${pkgs.xkcdpass}/bin/xkcdpass --numwords 10 > $out/random_password
'';

----



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.prompts



Prompts end up in $prompt/{zwsp}+<+{zwsp}name{gt} in the generator script



__Type:__ attribute set of (submodule)



__Default:__

[source,nix]
----
{ }
----



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.prompts{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.description



description shown during prompt entry



__Type:__ string



__Default:__

[source,nix]
----
"input for ‹name›"
----



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.serialization



Serialization definition



__Type:__ string



__Default:__

[source,nix]
----
config.artifacts.default.backend.serialization
----



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.shared



Whether this artifact is shared across multiple machines and/or home-manager configurations{zwsp}.

When ``true``, the artifact is generated once and distributed to all targets that define it{zwsp}. All definitions with the same artifact name and ``shared = true`` are aggregated together{zwsp}.

The backend must provide a ``shared{zwsp}.check`` and ``shared{zwsp}.serialize`` scripts to handle shared artifacts{zwsp}. The scripts receive a unified ``$targets`` environment variable pointing to a JSON file containing all target names, types, and their respective backend configurations{zwsp}.



__Type:__ boolean



__Default:__

[source,nix]
----
false
----


