== artifacts{zwsp}.default{zwsp}.backend{zwsp}.serialization

script for serialization



__Type:__ string



== artifacts{zwsp}.store



Artifacts store definitions



__Type:__ attribute set of (submodule)



__Default:__ ``{ }``



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.files



file definition on the target system



__Type:__ attribute set of (submodule)



__Default:__ ``{ }``



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.files{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.group



group of the file on the target system{zwsp}.



__Type:__ string



__Default:__ ``{quot}root{quot}``



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.files{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.mode



Permissions mode of the decrypted secret in a format understood by chmod{zwsp}.



__Type:__ string



__Default:__ ``{quot}0400{quot}``



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.files{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.name



The name of the filehandle



__Type:__ string __(read only)__



__Default:__ ``{quot}‹name›{quot}``



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.files{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.owner



owner of the file on the target system{zwsp}.



__Type:__ string



__Default:__ ``{quot}root{quot}``



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.files{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.path



Path to the file on the target system{zwsp}.



__Type:__ string



__Default:__ ``{quot}/run/artifacts/‹name›/‹name›{quot}``



__Example:__ ``{quot}/etc/ssh/ssh_host_ed25519_key{quot}``



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.generator



Generator Script{zwsp}. Two environment variables are handed over to this script{zwsp}.

[options="compact"]
* {empty}$prompt which is a folder containing files containing the prompt inputs (defined by the prompt option)

* {empty}$out which is a folder the generator script must create a file for each file definition of the artifact{zwsp}.




__Type:__ null or package



__Default:__ ``null``



__Example:__

----
pkgs.write.writeBash "random" ''
  ${pkgs.xkcdpass}/bin/xkcdpass --numwords 10 > $out/random_password
'';

----



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.name



The name of the artifact



__Type:__ string __(read only)__



__Default:__ ``{quot}‹name›{quot}``



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.prompts



Prompts end up in $prompt/{zwsp}+<+{zwsp}name{gt} in the generator script



__Type:__ attribute set of (submodule)



__Default:__ ``{ }``



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.prompts{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.description



description shown during prompt entry



__Type:__ string



__Default:__ ``{quot}input for ‹name›{quot}``



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.prompts{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.name



The name of the prompt



__Type:__ string __(read only)__



__Default:__ ``{quot}‹name›{quot}``



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.prompts{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.type



Type of prompt input



__Type:__ one of “hidden”, “line”, “multiline”



__Default:__ ``{quot}line{quot}``



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.serialization



Serialization definition



__Type:__ string



__Default:__ ``config{zwsp}.artifacts{zwsp}.default{zwsp}.backend{zwsp}.serialization``



== artifacts{zwsp}.store{zwsp}.{zwsp}+<+{zwsp}name{gt}{zwsp}.shared



Whether the store is shared



__Type:__ boolean



__Default:__ ``false``


