[test]
nixos_check_serialization = "./check.sh"
nixos_serialize = "./serialize.sh"
home_check_serialization = "./check.sh"
home_serialize = "./serialize.sh"

[test.capabilities]
shared = false
serializes = false
