site:
  title: NixOS Artifacts Documentation
  start_page: nixos-artifacts::index.adoc

content:
  sources:
    - url: ..
      start_path: docs
      branches: HEAD
    - url: https://github.com/mrVanDalo/nixos-artifacts-agenix.git
      start_path: docs
      branches: HEAD

antora:
  extensions:
    - require: "@sntke/antora-mermaid-extension"

ui:
  bundle:
    url: ../docs/ui-bundle.zip
    snapshot: true

output:
  dir: ../build/site
